mariadb:
  enabled: false
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      namespace: "monitoring"
elasticsearch:
  enabled: false
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      namespace: "monitoring"
mongodb:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
postgresqlha:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
mariadbgal:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
